-- CRM data lives in a private schema, outside Supabase's Data API.
-- Execute with a server-side Postgres connection, never from the browser.
CREATE SCHEMA IF NOT EXISTS crm;
SET search_path TO crm;

CREATE TABLE IF NOT EXISTS users(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'collaborator');
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'collaborator';
UPDATE users SET role='admin' WHERE id=(SELECT id FROM users ORDER BY id LIMIT 1) AND NOT EXISTS (SELECT 1 FROM users WHERE role='admin');
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id), csrf TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions(user_id);
CREATE TABLE IF NOT EXISTS campaigns(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, niche TEXT NOT NULL, city TEXT NOT NULL, district TEXT NOT NULL DEFAULT '', state TEXT NOT NULL, limit_count BIGINT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', apify_run_id TEXT, dataset_id TEXT, found BIGINT NOT NULL DEFAULT 0, saved BIGINT NOT NULL DEFAULT 0, enriched BIGINT NOT NULL DEFAULT 0, error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS district TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS saved_niches(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS saved_niches_name_unique ON saved_niches(LOWER(name));
CREATE TABLE IF NOT EXISTS leads(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, external_id TEXT UNIQUE, name TEXT NOT NULL, name_key TEXT NOT NULL, category TEXT, city TEXT, state TEXT, address TEXT, phone TEXT, phone_digits TEXT, website TEXT, instagram TEXT, facebook TEXT, marketplace TEXT, maps_url TEXT, rating DOUBLE PRECISION, reviews_count BIGINT, digital_status TEXT NOT NULL DEFAULT 'incerto', score BIGINT NOT NULL DEFAULT 0, stage TEXT NOT NULL DEFAULT 'novo', source TEXT NOT NULL DEFAULT 'manual', campaign_id BIGINT REFERENCES campaigns(id), offer TEXT, amount DOUBLE PRECISION, notes TEXT, next_action_at TEXT, reviewed BIGINT NOT NULL DEFAULT 0, blocked BIGINT NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS leads_lookup ON leads(name_key, city, state);
CREATE INDEX IF NOT EXISTS leads_stage ON leads(stage);
CREATE INDEX IF NOT EXISTS leads_campaign_id_idx ON leads(campaign_id);
CREATE TABLE IF NOT EXISTS observations(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE, kind TEXT NOT NULL, value TEXT, source_url TEXT, collected_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS observations_lead_recent ON observations(lead_id,id DESC);
CREATE TABLE IF NOT EXISTS activities(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE, kind TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS activities_lead_recent ON activities(lead_id,id DESC);
CREATE TABLE IF NOT EXISTS lead_lists(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS list_items(list_id BIGINT NOT NULL REFERENCES lead_lists(id) ON DELETE CASCADE, lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE, PRIMARY KEY(list_id, lead_id));
CREATE INDEX IF NOT EXISTS list_items_lead_id_idx ON list_items(lead_id);
CREATE TABLE IF NOT EXISTS suppression(phone_digits TEXT PRIMARY KEY, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS integrations(name TEXT PRIMARY KEY, secret TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS app_settings(name TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS collaborators(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, revoked_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS access_challenges(email TEXT PRIMARY KEY, code_hash TEXT NOT NULL, expires_at TEXT NOT NULL, attempts BIGINT NOT NULL DEFAULT 0, requested_at TEXT NOT NULL, requests BIGINT NOT NULL DEFAULT 1, window_started TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS access_sessions(token_hash TEXT PRIMARY KEY, email TEXT NOT NULL, csrf TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS collaborator_phones(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, phone TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, revoked_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS phone_challenges(phone TEXT PRIMARY KEY, code_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, attempts BIGINT NOT NULL DEFAULT 0, requested_at TEXT NOT NULL, requests BIGINT NOT NULL DEFAULT 1, window_started TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS phone_sessions(token_hash TEXT PRIMARY KEY, phone TEXT NOT NULL, csrf TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS access_login_limits(client_hash TEXT PRIMARY KEY, attempts BIGINT NOT NULL, started_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS phone_access_requests(phone TEXT PRIMARY KEY, requested_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS import_batches(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, city TEXT, state TEXT, list_id BIGINT REFERENCES lead_lists(id), total BIGINT NOT NULL DEFAULT 0, enriched BIGINT NOT NULL DEFAULT 0, failed BIGINT NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'queued', error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS import_batches_list_id_idx ON import_batches(list_id);
CREATE TABLE IF NOT EXISTS import_items(batch_id BIGINT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE, lead_id BIGINT NOT NULL REFERENCES leads(id), status TEXT NOT NULL DEFAULT 'pending', error TEXT, PRIMARY KEY(batch_id, lead_id));
CREATE INDEX IF NOT EXISTS import_items_lead_id_idx ON import_items(lead_id);
CREATE TABLE IF NOT EXISTS review_qr(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lead_id BIGINT NOT NULL UNIQUE REFERENCES leads(id) ON DELETE CASCADE, token TEXT NOT NULL UNIQUE, destination TEXT NOT NULL, scans BIGINT NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS local_jobs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE, kind TEXT NOT NULL, run_id TEXT, status TEXT NOT NULL DEFAULT 'queued', term TEXT, error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS local_documents(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE, kind TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS local_jobs_recent ON local_jobs(lead_id,kind,id DESC);
CREATE INDEX IF NOT EXISTS local_documents_recent ON local_documents(lead_id,kind,id DESC);
ALTER TABLE review_qr ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON review_qr FROM anon, authenticated;
ALTER TABLE local_jobs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON local_jobs FROM anon, authenticated;
ALTER TABLE local_documents ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON local_documents FROM anon, authenticated;

-- Authorization is checked in the Python API on every request.
CREATE TABLE IF NOT EXISTS google_users(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, revoked_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS google_sessions(token_hash TEXT PRIMARY KEY, email TEXT NOT NULL, csrf TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS oauth_states(token_hash TEXT PRIMARY KEY, verifier TEXT NOT NULL, expires_at TEXT NOT NULL);
